name: Deploy dine pleiepenger to dev
run-name: Deploy dine pleiepenger to dev (${{github.ref_name}})

on:
    workflow_dispatch:
    push:
        branches:
            - "innsyn**"

permissions: {}

jobs:
    deploy-to-dev:
        name: Deploy dine pleiepenger to dev
        if: github.event_name == 'workflow_dispatch' || contains(github.event.head_commit.message, '[to-dev]')
        uses: navikt/sif-brukerdialog/.github/workflows/.deploy-app-to-dev.yml@main
        secrets: inherit
        permissions:
            contents: read
            id-token: write
        with:
            app-name: "dine-pleiepenger"
            working-directory: "apps/dine pleiepenger"
            is-next-app: true
